service: stock-checker
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  environment:
    PASSWORD: ${file(./serverless.env.yml):PASSWORD, ''}
    SENDER_EMAIL: ${file(./serverless.env.yml):SENDER_EMAIL, ''}
    RECEIVER_EMAIL: ${file(./serverless.env.yml):RECEIVER_EMAIL, ''}

functions:
  bot:
    handler: main.check_store_stock
    events:
      - schedule: rate(5 minutes)

plugins:
  - serverless-python-requirements
